version: "3"
services:
  observer:
    image: grafana/grafana-oss:8.2.6
    restart: always
    ports:
      - 13300:3000
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
    driver: local
